---
title       : Sankar Vema
subtitle    : Digitial Leader, Solution Architect, Technology Enthusiast, AI Researcher
job         : Director - Technology at DXC Technology
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      #
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## About Me

1. Technology Leader
2. Seasoned architect
3.

LinkedIn: https://www.linkedin.com/in/sankarvema/
GitHub: http://sankarvema.github.io/
Blog: http://sankarvema.blogspot.com/
Twitter: https://twitter.com/sansvema
Ph: +91 888 611 0433 | +91 830 986 6887
Email: sans.vema@gmail.com


--- .class #id

## Career

#### Milestones
#### Onsite Engagements

---

## Clients

---
## Publications

---

## Open Source Projects

---

## Open Books

``` Open book concept follows the model of Open Source software development where book is available for the community based on Open Source license models. it does not have the standard publication limitation of the chapter and pages. Book effectively exploits that benefit and takes each subject from the basic concepts to practical applications or use cases to implementation scenarios and in some cases even to the development of sample models and code modules. As an open book this is constantly getting review, refined and augmented. More and more pages are being added every day.

•	Practical AI – is written with the objective of bring mapping most the advanced AI concepts to digital enterprises with more practical scenarios. https://github.com/SankarVema/PracticalAI-OpenBook
•	Microservices with JavaScript – being written based on experiences with the architecture and implementation of Talent Cloud platform. Most of the scenarios link to muTrixLabs


---

## Awards & Achievements

1.	DXC Distinguished Engineer – 2018
2.	CSC Distinguished Engineer – 2015
3.	CSC Horizon Award – 2014, Mr. Mike Lawrie, President & CEO, CSC
4.	AIC Club Award – 2006 & 2007, Mr. Subbu, Vice President, Satyam Computer Services Ltd.,
5.	Special Appreciation Award – Apr 2002 Dr. Ved Prakash Goyal. Cabinet Minister for Shipping, Govt. of India
6.	T. Swami Babu Medal & Sripathi Medal – 1998, Dr. APJ Kalam, Chief Scientist of India

---

## Interest

1. Explore next generation technologies especially in the area of AI and Quantum Computing
2. Programming Hacks, build app modules, architecture frameworks
3. God Theory, what it is?? ... "I do not know :( "
